name: Lint code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install linters
        run: |
          npm install -g eslint stylelint htmlhint jsonlint

      - name: Run HTMLHint
        run: htmlhint "**/*.html"

      - name: Run Stylelint
        run: stylelint "**/*.css"

      - name: Run ESLint
        run: eslint "**/*.js"

      - name: Run JSONLint
        run: |
          find . -name "*.json" -exec jsonlint -q {} \;
